stages:
  enhance:
    cmd: lyscripts data enhance data/2021-usz-oropharynx.csv data/enhanced.csv
    deps:
    - data/2021-usz-oropharynx.csv
    params:
    - modalities
    outs:
    - data/enhanced.csv
