stages:
  join:
    cmd: >
      lyscripts data join 
      -i data/2021-usz-oropharynx.csv
      data/2021-clb-oropharynx.csv
      data/2023-isb-multisite.csv
      data/2023-clb-multisite.csv
      data/2023-hvh-oropharynx.csv
      -o data/joined.csv
    deps:
    - data/2021-clb-oropharynx.csv
    - data/2021-usz-oropharynx.csv
    - data/2023-clb-multisite.csv
    - data/2023-isb-multisite.csv
    - data/2023-hvh-oropharynx.csv
    outs:
    - data/joined.csv

  enhance:
    cmd: lyscripts data enhance data/joined.csv data/enhanced.csv
    deps:
    - data/joined.csv
    params:
    - modalities
    outs:
    - data/enhanced.csv

  filter:
    cmd: lyscripts data filter data/enhanced.csv data/filtered.csv --include-subsites C01 C09 C10
    deps:
    - data/enhanced.csv
    outs:
    - data/filtered.csv

  reduce:
    cmd: python scripts/reduce.py data/filtered.csv data/reduced.csv
    deps:
    - data/filtered.csv
    - scripts/reduce.py
    outs:
    - data/reduced.csv

  sampling:
    foreach:
    - ipsi
    - contra
    - bilateral
    - midline
    do:
      cmd: >
        lyscripts sample
        --input data/reduced.csv
        --params models/${item}/params.yaml
        --output models/${item}/samples.hdf5
        --history models/${item}/history.csv
        --walkers-per-dim ${sampling.walkers_per_dim}
        --check-interval ${sampling.check_interval}
        --nsteps ${sampling.nsteps}
        --thin ${sampling.thin}
      deps:
      - data/reduced.csv
      params:
      - models/${item}/params.yaml:
      outs:
      - models/${item}/samples.hdf5
      - models/${item}/history.csv:
          cache: false

  compute-priors:
    foreach:
    - ipsi
    - contra
    - bilateral
    - midline
    do:
      cmd: >
        lyscripts compute priors
        --samples models/${item}/samples.hdf5
        --priors models/${item}/priors.hdf5
        --params models/${item}/params.yaml
        --scenarios scenarios.yaml
      deps:
      - models/${item}/samples.hdf5
      params:
      - models/${item}/params.yaml:
      - scenarios.yaml:
      outs:
      - models/${item}/priors.hdf5

  compute-posteriors:
    foreach:
    - ipsi
    - contra
    - bilateral
    - midline
    do:
      cmd: >
        lyscripts compute posteriors
        --priors models/${item}/priors.hdf5
        --posteriors models/${item}/posteriors.hdf5
        --params models/${item}/params.yaml
        --scenarios scenarios.yaml
      deps:
      - models/${item}/priors.hdf5
      params:
      - models/${item}/params.yaml:
      - scenarios.yaml:
      outs:
      - models/${item}/posteriors.hdf5

  compute-prevalences:
    foreach:
    - ipsi
    - contra
    - bilateral
    - midline
    do:
      cmd: >
        lyscripts compute prevalences
        --priors models/${item}/priors.hdf5
        --prevalences models/${item}/prevalences.hdf5
        --data data/reduced.csv
        --params models/${item}/params.yaml
        --scenarios scenarios.yaml
      deps:
      - models/${item}/priors.hdf5
      - data/reduced.csv
      params:
      - models/${item}/params.yaml:
      - scenarios.yaml:
      outs:
      - models/${item}/prevalences.hdf5

  compute-risks:
    foreach:
    - ipsi
    - contra
    - bilateral
    - midline
    do:
      cmd: >
        lyscripts compute risks
        --posteriors models/${item}/posteriors.hdf5
        --risks models/${item}/risks.hdf5
        --params models/${item}/params.yaml
        --scenarios scenarios.yaml
      deps:
      - models/${item}/posteriors.hdf5
      params:
      - models/${item}/params.yaml:
      - scenarios.yaml:
      outs:
      - models/${item}/risks.hdf5

  render-pdf:
    cmd: >
      quarto render manuscript.qmd --to pdf
    deps:
    - models
    - data/reduced.csv
    - manuscript.qmd
    outs:
    - manuscript.pdf
    - manuscript.tex
