vars:
  - _variables.yml

stages:
  join:
    cmd: >
      lyscripts data join 
      -i data/2021-usz-oropharynx.csv
      data/2021-clb-oropharynx.csv
      data/2023-isb-multisite.csv
      data/2023-clb-multisite.csv
      data/2023-hvh-oropharynx.csv
      -o data/joined.csv
    deps:
    - data/2021-clb-oropharynx.csv
    - data/2021-usz-oropharynx.csv
    - data/2023-clb-multisite.csv
    - data/2023-isb-multisite.csv
    - data/2023-hvh-oropharynx.csv
    outs:
    - data/joined.csv

  enhance:
    cmd: >
      lyscripts data enhance
      --params _variables.yml
      data/joined.csv data/enhanced.csv
    deps:
    - data/joined.csv
    params:
    - _variables.yml:
        - modalities
    outs:
    - data/enhanced.csv

  filter:
    cmd: lyscripts data filter data/enhanced.csv data/filtered.csv --include-subsites C01 C09 C10
    deps:
    - data/enhanced.csv
    outs:
    - data/filtered.csv

  reduce:
    cmd: python scripts/reduce.py data/filtered.csv data/reduced.csv
    deps:
    - data/filtered.csv
    - scripts/reduce.py
    outs:
    - data/reduced.csv

  sampling:
    matrix:
      model: [contra, bilateral, midline]
    cmd: >
      lyscripts sample
      --input data/reduced.csv
      --params models/${item.model}/params.yaml
      --output models/${item.model}/samples.hdf5
      --history models/${item.model}/history.csv
      --walkers-per-dim ${sampling.walkers_per_dim}
      --check-interval ${sampling.check_interval}
      --trust-fac ${sampling.trust_fac}
      --rel-thresh ${sampling.rel_thresh}
      --nsteps ${sampling.nsteps}
      --thin ${sampling.thin}
      --cores ${sampling.cores}
    deps:
    - data/reduced.csv
    params:
    - models/${item.model}/params.yaml:
    outs:
    - models/${item.model}/samples.hdf5
    - models/${item.model}/history.csv:
        cache: false

  compute-priors:
    matrix:
      model: [contra, bilateral, midline]
      scenario: [priors]
    cmd: >
      lyscripts compute priors
      --samples models/${item.model}/samples.hdf5
      --priors models/${item.model}/priors.hdf5
      --params models/${item.model}/params.yaml
      --scenarios scenarios/${item.scenario}.yaml
    deps:
    - models/${item.model}/samples.hdf5
    params:
    - models/${item.model}/params.yaml:
    - scenarios/${item.scenario}.yaml:
    outs:
    - models/${item.model}/${item.scenario}.hdf5

  # compute-posteriors:
  #   matrix:
  #     model: [contra, bilateral, midline]
  #     scenario: [base]
  #   cmd: >
  #     lyscripts compute posteriors
  #     --priors models/${item.model}/priors.hdf5
  #     --posteriors models/${item.model}/posteriors.hdf5
  #     --params models/${item.model}/params.yaml
  #     --scenarios scenarios/${item.scenario}.yaml
  #   deps:
  #   - models/${item.model}/priors.hdf5
  #   params:
  #   - models/${item.model}/params.yaml:
  #   - scenarios/${item.scenario}.yaml:
  #   outs:
  #   - models/${item.model}/posteriors.hdf5

  compute-prevalences:
    matrix:
      model: [contra, bilateral, midline]
      scenario: [overall, with_ipsi]
    cmd: >
      lyscripts compute prevalences
      --priors models/${item.model}/priors.hdf5
      --prevalences models/${item.model}/prevalences.hdf5
      --data data/reduced.csv
      --params models/${item.model}/params.yaml
      --scenarios scenarios/${item.scenario}.yaml
    deps:
    - models/${item.model}/priors.hdf5
    - data/reduced.csv
    params:
    - models/${item.model}/params.yaml:
    - scenarios/${item.scenario}.yaml:
    outs:
    - models/${item.model}/prevalences_${item.scenario}.hdf5

  # compute-risks:
  #   matrix:
  #     model: [contra, bilateral, midline]
  #     scenario: [overall, with_ipsi]
  #   cmd: >
  #     lyscripts compute risks
  #     --posteriors models/${item.model}/posteriors.hdf5
  #     --risks models/${item.model}/risks.hdf5
  #     --params models/${item.model}/params.yaml
  #     --scenarios scenarios/${item.scenario}.yaml
  #   deps:
  #   - models/${item.model}/posteriors.hdf5
  #   params:
  #   - models/${item.model}/params.yaml:
  #   - scenarios/${item.scenario}.yaml:
  #   outs:
  #   - models/${item.model}/risks.hdf5

  render-pdf:
    cmd: >
      quarto render manuscript.qmd --to pdf
    deps:
    - models
    - data/reduced.csv
    - manuscript.qmd
    outs:
    - _manuscript/manuscript.pdf
    - _manuscript/_tex/manuscript.tex
