version: 1                      # version of this parameter specification

########################################################################################
# This dictionary defines which LNLs are present in the
# graph and how they are connected.
graph:
  tumor:
    primary: [II, III]
  lnl:
    II: [III]
    III: []

########################################################################################
# Below are some parameters necessary for the model setup:
model:
  distributions:                # marginalize over diagnose times. Keys are T-stages
    early:
      frozen: binomial
      max_time: 10
      kwargs: {p: 0.3}
    late:
      parametric: binomial
      max_time: 10
  modalities: [max_llh]         # List of modalities, defined further down
  class: Midline                # model class to use (see `lymph-model` docs)
  # keyword arguments to pass to the model constructor
  kwargs:
    base_symmetric: false
    trans_symmetric: true
    use_mixing: true
    use_central: false
    use_midext_evo: true

########################################################################################
# Under this key we define the specficity and sensitivity for a range
# of diagnostic modalities. They are taken from literature and during
# sampling, everything that's not commented our here will be used for
# inference.
modalities:
  CT: [0.76, 0.81]
  MRI: [0.63, 0.81]
  PET: [0.86, 0.79]
  FNA: [0.98, 0.80]
  diagnostic_consensus: [0.86, 0.81]
  pathology: [1.0, 1.0]
  pCT: [0.86, 0.81]
  max_llh: [1.0, 1.0]

########################################################################################
# Here, we define sampling parameters
sampling:
  walkers_per_dim: 10
  check_interval: 50
  nsteps: 50
  thin: 1
